# Project information
site_name: 'Searchr'
site_description: 'Searchr'
site_author: 'Searchr'
site_url: 'https://squidfunk.github.io/mkdocs-material/'
theme:     'material'
site_favicon: 'images/favicon.ico'

# Repository
repo_name: 'shaunnarayan/searchr-wiki'
repo_url: 'https://github.com/shaunnarayan/searchr-wiki'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 Searchr'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascript/extra_js.js'
extra:
  palette:
    primary: 'blue grey'
    accent:  'cyan'
  logo:    'images/logo.svg'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/shaunnarayan'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/searchr/'
    - type: 'twitter'
      link: 'https://twitter.com/searchr'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/shoplex/'
  feature:
    tabs: false
pages:
  - Home: 'index.md'
  - Documentation:
    - Whitepaper: 'ico/whitepaper.pdf'
    - Multisigs:
      - Overview: 'documentation/multisigs/overview.md'
      - Foundation: 'documentation/multisigs/foundation.md'
    - Development Plan: 'documentation/Development_Plan.md'
    - Searchr Code of Conduct: 'documentation/Code_of_Conduct.md'
    - Community Content: 'documentation/community_content.md'
  - Development:
    - Overview: 'dev/index.md'
  - Meetings:
    - Community:
      - Community 01:
        - Agenda: 'meetings/community/01.md'
        - Write-Up - Luis: 'meetings/community/write-ups/cm01/luis.md'
  - Jobs:
    - Overview: 'jobs/index.md'
    - Openings:
      - EVM/Solidity Engineer: 'jobs/openings/solidity.md'
      - Frontend and web3 Developer: 'jobs/openings/frontend.md'
  - Blog posts:
    - 2018: 'blog/2018.md'
  - Videos:
    - Tutorials: 'videos/tutorials.md'
    - Meetings:
      - Community: 'videos/community.md'
  - Press:
      - Press Kit: 'press/press-kit.md'
      - Contact: 'press/contact.md'

